### ISSUE TITLE
beginning checklist

### ISSUE THREAD

**Issue by carlgombert** [carlgombert/Message-App-Backend#5]
- [ ] figure out how data will be structured in the database. I assume we will be storing user data as well as message history? to not overcrowd the database I think we should consider messages that delete after the user exits the message screen like snapchat
- [ ] figure out kinda how websockets work? I assume it would be going back and forth between the backend and frontend?
- [ ] figure out what API's the frontend will need
- [ ] read a lot and look at examples of how other messaging platforms are structured
